### ISSUE TITLE
class factory

### ISSUE THREAD

**Issue by macedogeo** [dmcarvalho/geo2local#1]
sou usuário do qgis e estou tentanto instalar seu complemento (win10 e qgis 3.4), portanto esta dando erro de método class factory, tens idéia do que pode ser?

esta caixa aparece quando se abre o qgis
e no final o erro python

Impossível carregar complemento 'geo2local-master' Devido a um erro ao chamar o método Class Factory(). 

ModuleNotFoundError: No module named 'sympy' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo2local-master\__init__.py", line 35, in classFactory
    from .geo2local import Geo2Local
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo2local-master\geo2local.py", line 34, in 
    from .converter.transformation import TransformationRT, TransformationNBR14166
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo2local-master\converter\transformation.py", line 15, in 
    from sympy.solvers import solve
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'sympy'

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versão do QGIS: 3.4.2-Madeira Madeira, 22034aa070 

Caminho do Python:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python

e o erro python

2019-03-25T09:22:37     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo2local-master\__init__.py", line 35, in classFactory
              from .geo2local import Geo2Local
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo2local-master\geo2local.py", line 34, in 
              from .converter.transformation import TransformationRT, TransformationNBR14166
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/maico/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geo2local-master\converter\transformation.py", line 15, in 
              from sympy.solvers import solve
              File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'sympy'
             

obrigado
maicon

**Comment by macedogeo** [comment]
sou usuário do qgis e estou tentanto instalar seu complemento (win10 e qgis 3.4), portanto esta dando erro de método class factory, tens idéia do que pode ser?

**Comment by yjmenezes** [comment]
@macedogeo 

Nao sei resolver em Kernel Windows.
Em Sistema Operacional  GNU/Linux  Debian 10.x e QGIS 3.12.0, resolve-se instalando python3-sympy
sudo apt-get update; sudo apt-get install python3-sympy

**Comment by macedogeo** [comment]
ok, muito obrigado, vou instalar no linuxEm Qui 26/03/20 19:34, julio cesar de menezes notifications@github.com escreveu:@macedogeoNao sei resolver em Kernel Windows.Em Sistema Operacional GNU/Linux Debian 10.x e QGIS 3.12.0, resolve-se instalando python3-sympysudo apt-get update; sudo apt-get install python3-sympy—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yjmenezes** [comment]
@macedogeo 

No Kernel Windows a solucao seria:

python3 -m pip install sympy

reporte se funcionou.


Aproveitando,  acho que vale a pena testar:

https://github.com/CaptainGinja/GnuWin32

**Comment by romariocarvalhoneto** [comment]
baixei hj e persiste o erro no windows. @yjmenezes, no meu caso o pip install levou meus arquivos para a pasta do C, do python padrão que uso em C:\Users\nomeDoUsuario\AppData\Local\Programs\Python\Python38\Lib\site-packages
Bastou copiar os arquivos baixados pelo pip install para a pasta do python que o QGIS usa em C:\Program Files\QGIS 3.10\apps\Python37\lib\site-packages que funcionou.
